name: Validate Static HTML and CSS

on:
  push:
    branches:
      - integration/login
      - integration/register
      - integration/css

jobs:
  validate-html-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install HTML/CSS validation tools
      - name: Install Validation Tools
        run: |
          npm install -g htmlhint stylelint

      - name: Validate Login Feature
        if: github.ref == 'refs/heads/integration/login'
        run: |
          echo "Validating login.html..."
          htmlhint ./integration/login/login.html || exit 1
          echo "Validating global.css..."
          stylelint ./integration/css/global.css || exit 1

      - name: Validate Register Feature
        if: github.ref == 'refs/heads/integration/register'
        run: |
          echo "Validating register.html..."
          htmlhint ./integration/register/register.html || exit 1
          echo "Validating global.css..."
          stylelint ./integration/css/global.css || exit 1

      - name: Validate Global CSS
        if: github.ref == 'refs/heads/integration/css'
        run: |
          echo "Validating global.css..."
          stylelint ./integration/css/global.css || exit 1
